name: Selenium Automation Run

on:
  push:
    branches: [ master ] 
  schedule:
    - cron: '0 4 * * *' 
  workflow_dispatch: 

jobs:
  automation-job:
    runs-on: ubuntu-22.04

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright Browsers
        run: |
          playwright install --with-deps chromium

      - name: Run Automation Tests
        env:
          RUN_ENV: server
          GITHUB_ACTIONS: true
          
          BUSINESS_URL: "https://my.rishonlezion.muni.il/business/"
          DAYCARE_URL: "https://my.rishonlezion.muni.il/daycare/"
          EDUCATION_URL: "https://my.rishonlezion.muni.il/education/"
          ENFORCEMENT_URL: "https://my.rishonlezion.muni.il/enforcement/"
          LOGIN_URL: "https://my.rishonlezion.muni.il/#/login"
          PARKING_URL: "https://my.rishonlezion.muni.il/parking/"
          STREET_URL: "https://my.rishonlezion.muni.il/street-info/"
          WATER_URL: "https://my.rishonlezion.muni.il/water/"
          HOME_URL_PART: "muni.il/"
          
          ID_NUMBER: ${{ secrets.ID_NUMBER }}
          PASSWORD: ${{ secrets.PASSWORD }}

        run: |
          pytest --alluredir=allure-results tests/test_full_flow.py

      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            screenshots/
            logs/
            allure-results/
          retention-days: 7
